name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    # The type of runner that the job will run on
    strategy:
      matrix:
        ro: [ubuntu-latest]
        lisp: [sbcl, ccl]
          # installation of quicklisp fails on Allegro for some
          # reason. Have to fix this later.

    runs-on: ${{ matrix.ro }}

    env:
      I_AGREE_TO_ALLEGRO_EXPRESS_LICENSE: yes

    container:
      image: clfoundation/${{matrix.lisp}}:latest

    steps:
    - name: install JSON wrangling binaries
      run: apt update && apt install -y jq python3 python3-pip && python3 -m pip install yq check-jsonschema

    - uses: actions/checkout@v3

    - run: install-quicklisp

    - name: install-modern-asdf
      run:
        mkdir /asdf && cd /asdf && wget https://asdf.common-lisp.dev/archives/asdf.lisp

    - name: SBCL
      if: ${{ matrix.lisp == 'sbcl' }}
      run: sbcl  --non-interactive
        --load /asdf/asdf.lisp
        --load $GITHUB_WORKSPACE/do-test.lisp
        --eval '(uiop:quit 0)'
    - name: Clozure
      if: ${{ matrix.lisp == 'ccl' }}
      run: ccl --batch
        --load /asdf/asdf.lisp
        --load $GITHUB_WORKSPACE/do-test.lisp
        --eval '(uiop:quit 0)'

  test-allegro:
    # The type of runner that the job will run on
    strategy:
      matrix:
        ro: [ubuntu-latest]
        lisp: [allegro]
          # installation of quicklisp fails on Allegro for some
          # reason. Have to fix this later.

    runs-on: ${{ matrix.ro }}

    env:
      I_AGREE_TO_ALLEGRO_EXPRESS_LICENSE: yes

    container:
      image: rpgoldman/allegro11express:latest

    steps:
    - name: install JSON wrangling binaries
      run: apt update && apt install -y jq python3 python3-pip && python3 -m pip install yq check-jsonschema

    - uses: actions/checkout@v3

    - run: install-quicklisp

    - name: install-modern-asdf
      run:
        mkdir /asdf && cd /asdf && wget https://asdf.common-lisp.dev/archives/asdf.lisp

    - name: Allegro
      run: alisp -L /asdf/asdf.lisp -L $GITHUB_WORKSPACE/do-test.lisp
        --kill
