name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    # The type of runner that the job will run on
    runs-on: ${{matrix.os}}

    container:
      image: clfoundation/${{matrix.lisp}}:latest

    strategy:
      matrix:
        os: [ubuntu-latest]
        lisp:
          - sbcl
          # - ccl
          # - allegro
          # installation of quicklisp fails on Allegro for some reason. Have to fix this later.

    env:
      I_AGREE_TO_ALLEGRO_EXPRESS_LICENSE: yes

    steps:
    - uses: actions/checkout@v3

    - run: install-quicklisp

    - name: install-modern-asdf
      run:
        mkdir /asdf && cd /asdf && wget https://asdf.common-lisp.dev/archives/asdf.lisp

    - name: SBCL
      if: ${{ matrix.lisp == 'sbcl' }}
      run: sbcl  --non-interactive
        --load /asdf/asdf.lisp
        --load $GITHUB_WORKSPACE/do-test.lisp
        --eval '(uiop:quit 0)'
    # - name: Allegro
    #   if: ${{ matrix.lisp == 'allegro' }}
    #   run: alisp -L /github/home/quicklisp/setup.lisp
    #     -e "(asdf:load-asd \"$GITHUB_WORKSPACE/random-state.asd\")" 
    #     -e '(ql:quickload "random-state/tests")'
    #     -e '(asdf:test-system "random-state")'
    #     --kill
    - name: Clozure
      if: ${{ matrix.lisp == 'ccl' }}
      run: ccl --batch
        --load /asdf/asdf.lisp
        --load $GITHUB_WORKSPACE/do-test.lisp
        --eval '(uiop:quit 0)'
